export const GET_ALL_GENRES_REQUEST = "GET_ALL_GENRES_REQUEST";
export const GET_ALL_GENRES_SUCCESS = "GET_ALL_GENRES_SUCCESS";
export const GET_ALL_GENRES_FAILURE = "GET_ALL_GENRES_FAILURE";

export const ADD_GENRES_REQUEST = "ADD_GENRES_REQUEST";
export const ADD_GENRES_SUCCESS = "ADD_GENRES_SUCCESS";
export const ADD_GENRES_FAILURE = "ADD_GENRES_FAILURE";

export const UPDATE_GENRES_REQUEST = "UPDATE_GENRES_REQUEST";
export const UPDATE_GENRES_SUCCESS = "UPDATE_GENRES_SUCCESS";
export const UPDATE_GENRES_FAILURE = "UPDATE_GENRES_FAILURE";
