export const GET_MOVIE_AND_SERIES_REQUEST = "GET_MOVIE_AND_SERIES_REQUEST";
export const GET_MOVIE_AND_SERIES_SUCCESS = "GET_MOVIE_AND_SERIES_SUCCESS";
export const GET_MOVIE_AND_SERIES_FAILURE = "GET_MOVIE_AND_SERIES_FAILURE";
