export const GET_MOVIE_AND_SERIES_REQUEST = "GET_MOVIE_AND_SERIES_REQUEST";
export const GET_MOVIE_AND_SERIES_SUCCESS = "GET_MOVIE_AND_SERIES_SUCCESS";
export const GET_MOVIE_AND_SERIES_FAILURE = "GET_MOVIE_AND_SERIES_FAILURE";

export const LIKE_MOVIE_AND_SERIES_REQUEST = "LIKE_MOVIE_AND_SERIES_REQUEST";
export const LIKE_MOVIE_AND_SERIES_SUCCESS = "LIKE_MOVIE_AND_SERIES_SUCCESS";
export const LIKE_MOVIE_AND_SERIES_FAILURE = "LIKE_MOVIE_AND_SERIES_FAILURE";

export const DELETE_LIKE_MOVIE_AND_SERIES_REQUEST =
  "DELETE_LIKE_MOVIE_AND_SERIES_REQUEST";
export const DELETE_LIKE_MOVIE_AND_SERIES_SUCCESS =
  "DELETE_LIKE_MOVIE_AND_SERIES_SUCCESS";
export const DELETE_LIKE_MOVIE_AND_SERIES_FAILURE =
  "DELETE_LIKE_MOVIE_AND_SERIES_FAILURE";
