export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILURE = "ADD_MOVIE_FAILURE";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAILURE = "UPDATE_MOVIE_FAILURE";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILURE = "DELETE_MOVIE_FAILURE";

export const GET_ALL_MOVIE_REQUEST = "GET_ALL_MOVIE_REQUEST";
export const GET_ALL_MOVIE_SUCCESS = "GET_ALL_MOVIE_SUCCESS";
export const GET_ALL_MOVIE_FAILURE = "GET_ALL_MOVIE_FAILURE";

export const GET_DETAIL_MOVIE_REQUEST = "GET_DETAIL_MOVIE_REQUEST";
export const GET_DETAIL_MOVIE_SUCCESS = "GET_DETAIL_MOVIE_SUCCESS";
export const GET_DETAIL_MOVIE_FAILURE = "GET_DETAIL_MOVIE_FAILURE";

export const COMMENT_MOVIE_REQUEST = "COMMENT_MOVIE_REQUEST";
export const COMMENT_MOVIE_SUCCESS = "COMMENT_MOVIE_SUCCESS";
export const COMMENT_MOVIE_FAILURE = "COMMENT_MOVIE_FAILURE";
