export const ADD_SERIES_REQUEST = "ADD_SERIES_REQUEST";
export const ADD_SERIES_SUCCESS = "ADD_SERIES_SUCCESS";
export const ADD_SERIES_FAILURE = "ADD_SERIES_FAILURE";

export const UPDATE_SERIES_REQUEST = "UPDATE_SERIES_REQUEST";
export const UPDATE_SERIES_SUCCESS = "UPDATE_SERIES_SUCCESS";
export const UPDATE_SERIES_FAILURE = "UPDATE_SERIES_FAILURE";

export const DELETE_SERIES_REQUEST = "DELETE_SERIES_REQUEST";
export const DELETE_SERIES_SUCCESS = "DELETE_SERIES_SUCCESS";
export const DELETE_SERIES_FAILURE = "DELETE_SERIES_FAILURE";

export const GET_ALL_SERIES_REQUEST = "GET_ALL_SERIES_REQUEST";
export const GET_ALL_SERIES_SUCCESS = "GET_ALL_SERIES_SUCCESS";
export const GET_ALL_SERIES_FAILURE = "GET_ALL_SERIES_FAILURE";

export const GET_DETAIL_SERIES_REQUEST = "GET_DETAIL_SERIES_REQUEST";
export const GET_DETAIL_SERIES_SUCCESS = "GET_DETAIL_SERIES_SUCCESS";
export const GET_DETAIL_SERIES_FAILURE = "GET_DETAIL_SERIES_FAILURE";

export const DELETE_EPISODE_SERIES_REQUEST = "DELETE_EPISODE_SERIES_REQUEST";
export const DELETE_EPISODE_SERIES_SUCCESS = "DELETE_EPISODE_SERIES_SUCCESS";
export const DELETE_EPISODE_SERIES_FAILURE = "DELETE_EPISODE_SERIES_FAILURE";

export const UPDATE_EPISODE_SERIES_REQUEST = "UPDATE_EPISODE_SERIES_REQUEST";
export const UPDATE_EPISODE_SERIES_SUCCESS = "UPDATE_EPISODE_SERIES_SUCCESS";
export const UPDATE_EPISODE_SERIES_FAILURE = "UPDATE_EPISODE_SERIES_FAILURE";
